# Generated by Django 3.2 on 2021-08-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['product', 'text', 'author']},
        ),
    ]
