# Generated by Django 3.2 on 2021-09-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('likes', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'ordering': ['title', 'address'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
