# Generated by Django 3.2 on 2021-08-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productreview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
    ]
