# Generated by Django 3.2 on 2021-09-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210902_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='value',
            new_name='liked',
        ),
    ]
